# Generated by Django 3.1.3 on 2020-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='recordsUser',
            field=models.ManyToManyField(to='accounts.records'),
        ),
    ]
